events {}
http {
        server {
                listen 80;
		location / {
			root /home/ec2-user/VT-Demo/project/frontend;
		}
                location /api {
                        proxy_pass http://localhost:5000/api;
                }
        }
}