events {}
http {
        server {
                listen 80;
		location / {
			root /home/ec2-user/vt-project-combined/frontend;
		}
                location /api {
                        proxy_pass http://localhost:5000/api;
                }
        }
}